### ISSUE TITLE
Code is not transpiled to ES5

### ISSUE THREAD

**Issue by einarlove** [mcernusca/use-key-state#3]
If you install this and import it you'll get `SyntaxError: Unexpected token import`.

Suggest you add a rollup config and release something compiled to something parseable by browsers.

**Comment by mcernusca** [comment]
Thanks, on it 👍

**Comment by mcernusca** [comment]
@einarlove try out 0.1.8

**Comment by einarlove** [comment]
Somethings up with the export.
```js
import useKeyState from 'use-key-state' // undefined
import { useKeyState } from 'use-key-state' // undefined
import * as useKeyState from 'use-key-state' // { default: { useKeyState: Function } …}
```
